### ISSUE TITLE
Wrong K8s's info for the node-exporter and kindling-agent

### ISSUE THREAD

**Issue by NeJan2020** [CloudDectective-Harmonycloud/kindling#201]
**Describe the bug**
1. node-exporter
<img width="742" alt="image" src="https://user-images.githubusercontent.com/64676199/165699873-d2c819be-e7e3-4cb4-aa41-048a902a67f1.png">
we can see node-exporter has a topology to `127.0.0.1:9100`, which makes me confused since this port is listened by itself

2. kindling-agent
<img width="590" alt="image" src="https://user-images.githubusercontent.com/64676199/165700272-08fce882-ed74-42d9-8983-6ea74a362f8c.png">
Most `daemonset` is marked as an unknow service, such as kindling-agent.

**How to reproduce?**
Installing node-exporter and check topology.

**What did you expect to see?**

Real topology of node-exporter: 
prometheus->node-exporter(container: kube-rbac-proxy)->node-exporter(container:  node-exporter)

Real topology of kindling-agent:
prometheus->kindling-agent

**Comment by dxsup** [comment]
These two bugs are caused by different reasons.
1. As you say, the destination IP is `127.0.0.1` which should be dealt with in a different way but we didn't before. #251 has fixed this issue.
2. The pod `kindling-agent` is using `hostNetwork` and the ports it is listening on are not specified in its declaration yaml file, in which case we can't know the pod via `IP:Port`. I have no ideas on how to fix this now.

**Comment by dxsup** [comment]
Since there is no way to work around the `hostNetwork` case now, we declared the port listened by Kindling in its yaml(#282). So currently, it can be seen in the topology.
<img width="870" alt="image" src="https://user-images.githubusercontent.com/46807570/177524969-defdae1c-330a-4584-b373-221b504dd5cc.png">
